// Books
export const SET_FETCHED_BOOKS = 'SET_FETCHED_BOOKS'
export const SET_FETCHED_BOOK = 'SET_FETCHED_BOOK'

// Navigation

export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD'
export const NAVIGATION_BACK = 'NAVIGATION_BACK'
