// Books
export const SET_FETCHED_ENTRIES = 'SET_FETCHED_ENTRIES'
export const SET_FETCHED_ENTRY = 'SET_FETCHED_ENTRY'

// Navigation

export const NAVIGATION_FORWARD = 'NAVIGATION_FORWARD'
export const NAVIGATION_BACK = 'NAVIGATION_BACK'
